export const GET_CRYPTO_LATEST_LISTING = 'GET_CRYPTO_LATEST_LISTING';
export const SET_CURRENCY = 'SET_CURRENCY';
export const GET_TRENDING_LISTS = 'GET_TRENDING_LISTS';
export const SET_LATEST_NEWS = 'SET_LATEST_NEWS';
export const SET_TOP_VOLUMN_LIST = 'SET_TOP_VOLUMN_LIST';
export const WEB_SOCKET_AGGIGATE_INDEX = 'WEB_SOCKET_AGGIGATE_INDEX';