// export { default as CryptoLatestListing } from './latestlisting1';
export { default as CryptoLatestListing } from './latestlisting';
export { default as SelectCurrency } from './selectCurency';
export { WidgetTradingView } from './TradingViewWidget';
export { default as CoinmarketGetCryptoBySymbol } from './coinmarketListingById';
export {default as CoinmarketTrends} from './coinmarketTrends';
export {default as LatestNews} from './latestNews';
export { default as CryptoTopNavBar} from './navbars/top';
export { default as TopVolumnList} from './cryptocompare/top_volumn_list';
export {default as AggrigateIndex} from './cryptocompare/web_socket_aggrigate';